server:
  port: 8899

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://144.24.87.198:5432/junny
    username: junny
    password: 1234
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: create
    database: postgresql